name: Daily Meal Notification

on:
  schedule:
    # 매일 오후 1시 30분 KST (UTC 04:30)
    - cron: '30 4 * * *'
  workflow_dispatch: # 수동 실행 가능

jobs:
  send-meal:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Send meal to Slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      run: python send_meal_to_slack.py 